server:
 port: 8081
 servlet:
  context-path: /active
spring:
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: LEGACYHTML5 # 用非严格的 HTML   ,HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

  devtools:
     restart:
  #热部署页面自动刷新
      enabled: true
  #热部署扫描支持的目录
      additional-paths: src/main/java
  #指定热部署的页面
      exclude: static/**
     livereload:
      enabled: true

#消息队列配置
#  activemq:
#    user: admin
#    password: admin
#    #本机的地址
#    broker-url: tcp://192.168.43.23:61616
#    pool:
#      enabled: true
#      max-connections: 10
queueName: publish.queue
topicName: publish.topic
